certFile: "./rootCertificate.pem"
certKey: "./rootPrivateKey.pem"
proxyPort: 12345
tunnelPort: 12000
icapServerReqUrl: "icap://test-icap-server.com:27000/request"
icapServerRespUrl: "icap://test-icap-server.com:27000/response"
forwardProxyAddress: "test-proxy-server.com:50652"